### ISSUE TITLE
Is there a minimal working example to use smeagol-galore with a LDAP server for user auth?

### ISSUE THREAD

**Issue by Tony2** [schnatterer/smeagol-galore#9]
Hi,

I read that LDAP auth is possible via CAS. Is is possible to have a minimal working example how to run smeagol-galore with LDAP auth (for example with JumpCloud)? It would be much appreciated, since I have never used CAS before.

**Comment by schnatterer** [comment]
Hi @Tony2,

 [cloudogu/cas](https://github.com/cloudogu/cas/) uses LDAP. It's not minimal, and uses openldap (not jumpcloud), though.
Note that they're updating to cas 6 at moment, so I presume smeagol galore will also upgrade in the not so far future.
For now, smeagol galore uses cas 4, so maybe [the docs](https://apereo.github.io/cas/4.0.x/index.html) can help.
Closing this because I consider it more of a question than an actual issue.

**Comment by Tony2** [comment]
Hi @schnatterer,

thank you for the hint. Here is my understanding of what is needed to be done to get LDAP auth:

- clone this repo
- make change to deployerConfigContext.xml, as instructed in https://apereo.github.io/cas/4.1.x/installation/LDAP-Authentication.html
- build the docker image and start a container from it, instead of the official docker image

Is this correct, or am I still missing some step?
